In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score


In [2]:
df = pd.read_csv('/content/wine.csv') 
print(df.shape)
df.describe().transpose()

(178, 14)


count        mean         std     min       25%  \
Wine                  178.0    1.938202    0.775035    1.00    1.0000   
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic.acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Acl                   178.0   19.494944    3.339564   10.60   17.2000   
Mg                    178.0   99.741573   14.282484   70.00   88.0000   
Phenols               178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid.phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanth               178.0    1.590899    0.572359    0.41    1.2500   
Color.int             178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD                    178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Wine                    2.000    3.0000     3.00  
Alcohol                13.050   13.6775    14.83  
Malic.acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Acl                    19.500   21.5000    30.00  
Mg                     98.000  107.0000   162.00  
Phenols                 2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid.phenols    0.340    0.4375     0.66  
Proanth                 1.555    1.9500     3.58  
Color.int               4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD                      2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [3]:
df

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065  
1                    0.26     1.28       4.38  1.05  3.40     1050  
2                    0.30     2.81       5.68  1.03  3.17     1185  
3                    0.24     2.18       7.80  0.86  3.45     1480  
4                    0.39     1.82       4.32  1.04  2.93      735  
..                    ...      ...        ...   ...   ...      ...  
173                  0.52     1.06       7.70  0.64  1.74      740  
174                  0.43     1.41       7.30  0.70  1.56      750  
175                  0.43     1.35      10.20  0.59  1.56      835  
176                  0.53     1.46       9.30  0.60  1.62      840  
177                  0.56     1.35       9.20  0.61  1.60      560  

[178 rows x 14 columns]

In [4]:
X = df.drop('Wine',axis=1)
y = df['Wine']

In [5]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
%%time

from sklearn.model_selection import GridSearchCV

params = {'activation': ['relu', 'tanh', 'logistic', 'identity'],
          'hidden_layer_sizes': [(13,), (50,100,), (50,75,100,)],
          'solver': ['adam', 'sgd', 'lbfgs'],
          'learning_rate' : ['constant', 'adaptive', 'invscaling'],
          'max_iter': [700]
         }

mlp_classif_grid = GridSearchCV(MLPClassifier(random_state=123), param_grid=params, n_jobs=-1, cv=5, verbose=5)
mlp_classif_grid.fit(X_train,y_train)

print('Train Accuracy : %.3f'%mlp_classif_grid.best_estimator_.score(X_train, y_train))
print('Test Accuracy : %.3f'%mlp_classif_grid.best_estimator_.score(X_test, y_test))
print('Best Accuracy Through Grid Search : %.3f'%mlp_classif_grid.best_score_)
print('Best Parameters : ',mlp_classif_grid.best_params_)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
Train Accuracy : 1.000
Test Accuracy : 0.933
Best Accuracy Through Grid Search : 1.000
Best Parameters :  {'activation': 'tanh', 'hidden_layer_sizes': (13,), 'learning_rate': 'constant', 'max_iter': 700, 'solver': 'adam'}
CPU times: user 2.24 s, sys: 214 ms, total: 2.45 s
Wall time: 1min 58s


In [8]:
mlp = MLPClassifier(activation= 'relu', hidden_layer_sizes= (13,), learning_rate='constant', solver='adam', max_iter=700)


In [9]:
mlp.fit(X_train,y_train)


MLPClassifier(hidden_layer_sizes=(13,), max_iter=700)

In [10]:
predictions = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix


In [12]:
print(confusion_matrix(y_test,predictions))


[[12  0  0]
 [ 2 16  1]
 [ 0  0 14]]


In [13]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.86      1.00      0.92        12
           2       1.00      0.84      0.91        19
           3       0.93      1.00      0.97        14

    accuracy                           0.93        45
   macro avg       0.93      0.95      0.93        45
weighted avg       0.94      0.93      0.93        45

